laserscan_multi_merger:
  ros__parameters:
    destination_frame: "lidar_merge_link"
    cloud_destination_topic: "/forklift_bruce/merged_cloud"
    scan_destination_topic: "/forklift_bruce/scan"
    laserscan_topics: "/forklift_bruce/left/scan /forklift_bruce/right/scan"
    angle_min: -360.0
    angle_max: 360.0
    angle_increment: 0.00437
    scan_time: 0.0
    range_min: 0.1
    range_max: 20.0

